theme: jekyll-theme-slate
---
title: "Work Plan"
author: "Tiara Verweij"
date: "26-5-2021"
output: html_document
runtime: shiny
---

## My workplan

**Why Shiny App?**

I had to work with shiny for the first time during the master classes and the projecticum. After the masterclass, I didn't feel like I understood everything about Shiny, so I was often looking up examples and trying to understand them better. Therefore, I chose to spend the 4 days we had to learn more about Shiny in relation to our project.

**Spending the first 2 days practising**

Because I am already familiar with Shiny App, I don't need a lot of time to do research. The website I found is actually a deepening of the master class, so it helped me a lot (1)(2). I needed 1-2 days to finish this master class. 

**Building my own Shiny App**

After practising with Shiny, it is really time to start making my own Shiny App. I plan to use the dataset we have for our project as input for my Shiny App. I plan to look up summarized experiments from similar datasets to make sure this dataset looks the same. Once this is done, I plan to dissect different Shiny apps and look at the graphs and tables used. I will then use these for my datasets as well. 

**What will my Shiny App look like?**

I want my Shiny app to be clear, so I'll be adding lots of comments. I also want to make an app with more difficult graphs instead of tables, because I find graphs more of a challenge. For the type of dataset I have chosen (transcription analysis) I would like to add heat maps and vulcano plots because I see these are used more often for transcription analysis. 

(1)https://mastering-shiny.org/basic-app.html
(2)https://towardsdatascience.com/how-to-build-a-data-analysis-app-in-r-shiny-143bee9338f7

```{r setup, echo=FALSE}
library(shiny)
```
```{r}
ui <- fluidPage(
  selectInput("dataset", label = "Dataset", choices = ls("package:datasets")),
  verbatimTextOutput("summary"),
  tableOutput("table")
)
server <- function(input, output, session) {
  # Create a reactive expression
  dataset <- reactive({
    get(input$dataset, "package:datasets")
  })
  output$summary <- renderPrint({
    # Use a reactive expression by calling it like a function
    summary(dataset())
  })
  
  output$table <- renderTable({
    dataset()
  })
}
shinyApp(ui, server)
```
