---
title: "My Longterm goals"
author: "Tiara Verweij"
date: "20-5-2021"
output: html_document
---

**My two year plan**

first of all i want to get my bachelor's degree. i would also like to do my internship in data science alongside my minor in data science. it would be great to find a job at the Westdijk institute in the database/software department. this company does a lot of research into yeasts and food, and i find that really interesting because i already know a lot about food. They also have often job openings for biomedici.  I am also very enthusiastic about Genmab BV, a company specialising in the creation and development of differentiated antibody therapeutics for the treatment of cancer. the only downside to this company is that they don't have an opening in data science yet.  Finally, I would ideally like to find a job at Skyline Dx, this is a company driven by scientific and data research in the field of molecular diagnostics. this company also has a biomedical research position as well as a bioinformatics position so this would be perfect for me.

At the moment, I am trying to find an internship that has both a data science side and a biomolecular research side. I enjoy doing research into genes the most.  I would like to find an internship that allows me to work as an employee afterwards.  

during my free time i am working on developing my skills with Shiny App, because many companies are already working on it. in addition, i find it very interesting to work on Shiny and it fits well with my projects. 



